Ramen/urls.py
from django.urls import path
from .views import index_views, index_5_oder_comp, index_3_voice_oder, index_0_cspower_on, db_index00

app_name = 'Ramen'

urlpatterns = [

    path('', index_views.index, name='index'), # 제일 초기 화면
    path('index02/', index_views.oder_select, name='index02'), # 일반주문 / 음성주문 선택화면
    path('index03/', index_3_voice_oder.voice_oder, name='index03'), # 음성인식 주문화면
    path('index04/', index_views.manual_oder, name='index04'), # 일반주문 화면
    # path('index05/', index_5_oder_comp.manual_oder_complete, name='index05'), # 일반주문 확인 완료
    path('index05/<int:count>/<str:employee_id>/', index_5_oder_comp.manual_oder_complete, name='index05'), # 일반주문 확인 완료

    # WARNING : db전송 확인 코드
    # 로그인 관련 URL 패턴
    path('db_index00/', db_index00.login_view, name='db_index00'),  # 로그인 페이지

    # 음성주문에 관한 것들 미사용
    # path('voice-order/', index_3_voice_oder.voice_oder, name='voice_order'),
    # path('test-microphone/', index_3_voice_oder.test_microphone_view, name='test_microphone_view'),
    # path('index05/', index_3_voice_oder.index05, name='index05'),  # index05 뷰에 대한 URL 패턴 추가
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from Ramen.views import index_views, index_0_cspower_on
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('', index_views.index, name='index'),
    path('', index_0_cspower_on.cs_poweron, name='init'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('Ramen/', include('Ramen.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
]

Ramen/models.py
from django.db import models
from datetime import datetime

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class MyModel(models.Model):
    date = models.DateTimeField()  # auto_now_add 제거
    employee_id = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    count = models.IntegerField()

    def save(self, *args, **kwargs):
        # 현재 시간을 초 단위까지만 저장
        if not self.date:
            self.date = datetime.now().replace(microsecond=0)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.date} - {self.employee_id} - {self.name} - {self.count}'

Ramen/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

#메인 화면 첫화면
def index(request):
    return render(request, './index.html')

Ramen/views/db_index00.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from ..models import MyModel  # 상위 디렉토리의 models.py 파일에서 MyModel을 가져옵니다

def login_view(request):
    if request.method == 'POST':
        employee_id = request.POST.get('employee_id')
        password = request.POST.get('password')
        count = request.POST.get('count')  # POST 요청에서 count 값을 받음

        # count 값이 빈 문자열일 경우 처리
        try:
            count = int(count)
        except (TypeError, ValueError):
            count = 0

        # 사번과 비밀번호로 사용자 인증
        user = authenticate(request, username=employee_id, password=password)

        if user is not None:
            login(request, user)

            # 로그인한 사용자의 User 객체를 MyModel의 employee 필드에 저장
            my_model_instance = MyModel(
                employee_id=employee_id, 
                name=user.first_name,  # 이름을 User 모델의 first_name 필드에서 가져옵니다.
                count=count
            )
            my_model_instance.save()

            # 사번과 count 값을 index05로 넘김
            return redirect('Ramen:index05', count=count, employee_id=employee_id)  # 로그인 성공 시 index05로 리디렉션
        else:
            messages.error(request, '사번 또는 비밀번호 확인하세요!!')
            # 로그인 실패 시에도 count 값을 유지하며 다시 로그인 페이지를 렌더링
            return render(request, 'ramen/db_index00.html', {
                'count': count,
                'employee_id': employee_id
            })

    # GET 요청 시에도 count 값을 유지하도록 처리
    count = request.GET.get('count', 0)
    return render(request, 'ramen/db_index00.html', {'count': count})

Ramen/views/index_0_cspower_on.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
import time
import socket, time
from _thread import *
import logging

def cs_poweron(request):
    print(": 초기협동부팅")
    ip='192.168.1.20'
    port=29999  #29999 직접 제어

    # 서버의 주소입니다. hostname 또는 ip address를 사용할 수 있습니다.
    HOST = ip 
    # 서버에서 지정해 놓은 포트 번호입니다. 
    PORT = port       

    # 소켓 객체를 생성합니다. 
    # 주소 체계(address family)로 IPv4, 소켓 타입으로 TCP 사용합니다.  
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    # 지정한 HOST와 PORT를 사용하여 서버에 접속합니다. 
    ck=client_socket.connect((HOST, PORT))

    data="robotControl -on"
    data=data+"\n"
    print(": 협동전원 On")

    client_socket.sendall(data.encode())
    time.sleep(10)
    data="brakeRelease"+"\n"
    client_socket.sendall(data.encode())
    print(": 협동브레이크 off")


    return render(request, './ramen/init_cs_power.html')

Ramen/views/index_3_voice_oder.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from pyModbusTCP.client import ModbusClient
import speech_recognition as sr
import time

plc_ip = "192.168.1.10"
mainPlc = ModbusClient(host=plc_ip, unit_id=1, auto_open=True, auto_close=True)

def voice_oder(request):
    return render(request, './ramen/new_index03.html')

def test_microphone_view(request):
    if request.method == 'POST':
        result = test_microphone()
        if result:
            # 주문이 정상적으로 처리되면 count 값을 가지고 new_index05.html로 리다이렉트
            return JsonResponse({'status': 'redirect', 'url': f'/Ramen/index05/?count={result}'})
        else:
            # 주문 실패 시 index02로 리다이렉트
            return JsonResponse({'status': 'redirect', 'url': '/Ramen/index02/'})
    return JsonResponse({'status': 'error', 'message': '잘못된 요청입니다.'})

def test_microphone(device_index=None):
    recognizer = sr.Recognizer()
    command_map = {
        '한 개': 1, '하나': 1, '한 그릇': 1,
        '두 개': 2, '둘': 2, '두 그릇': 2,
        '세 개': 3, '셋': 3, '세 그릇': 3,
        '네 개': 4, '넷': 4, '네 그릇': 4,
        '다섯 개': 5, '다섯': 5, '다섯 그릇': 5,
        '여섯 개': 6, '여섯': 6, '여섯 그릇': 6,
        '일곱 개': 7, '일곱': 7, '일곱 그릇': 7,
        '여덟 개': 8, '여덟': 8, '여덟 그릇': 8,
        '아홉 개': 9, '아홉': 9, '아홉 그릇': 9,
        # '열 개': 10, '열': 10, '열그릇': 10
    }

    try:
        with sr.Microphone(device_index=device_index) as source:
            recognizer.adjust_for_ambient_noise(source)
            print("주문수량을 말씀해 주세요.")
            print("plz oder")
            audio = recognizer.listen(source)
            time.sleep(2)
            try:
                print("주문 수량 확인중...")
                print("check oder")
                text = recognizer.recognize_google(audio, language="ko-KR")
                # print(f"오더수량: {text}")
                for command, value in command_map.items():
                    if command in text:
                        mainPlc.write_multiple_registers(5010, [40])
                        mainPlc.write_multiple_registers(5000, [value])
                        print(f"{value}개 주문이 실행되었습니다.")
                        print(f"{value}comp.")
                        return value
                print("명령어가 인식되지 않았습니다.")
                print("oder miss")
                return None
            except sr.UnknownValueError:
                print("음성을 명확하게 인식할 수 없습니다.")
                print("voice erro")
                return None
            except sr.RequestError as e:
                print(f"음성 인식 서비스에 접근할 수 없습니다: {e}")
                print(f"sservice not define: {e}")
                return None
    except Exception as e:
        print(f"오류가 발생했습니다: {e}")
        print(f"er: {e}")
        return None


def index05(request):
    count = request.GET.get('count', 0)  # URL 파라미터에서 count 값을 가져옵니다.
    return render(request, './ramen/new_index05.html', {'count': count})

Ramen/views/index_5_oder_comp.py
from django.shortcuts import render
from pyModbusTCP.client import ModbusClient

plc_ip = "192.168.20.100"
mainPlc = ModbusClient(host=plc_ip, unit_id=1, auto_open=True, auto_close=True)

def manual_oder_complete(request, count, employee_id):
    plc_oder_count = int(count)
    print(": 주문수량 :", plc_oder_count)
    
    # PLC 명령 전송
    mainPlc.write_multiple_registers(5010, [40])
    mainPlc.write_multiple_registers(5000, [plc_oder_count])
    
    # count와 employee_id 값을 템플릿으로 전달
    return render(request, './ramen/new_index05.html', {'count': count, 'employee_id': employee_id})

Ramen/views/index_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
import time

#메인 화면 첫화면

def index(request):
    return render(request, './ramen/new_index.html')

def oder_select(request):
    return render(request, './ramen/new_index02.html')

def manual_oder(request):
    return render(request, './ramen/new_index04.html')

templates/ramen/db_index00.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/db_style00.css' %}">
</head>
<body>
    <div class="login-container">
        <h2>결재 정보</h2>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form action="{% url 'Ramen:db_index00' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="count" value="{{ count }}">
            <label for="employee_id">사원 번호</label>
            <input type="text" id="employee_id" name="employee_id" required>
            
            <label for="password">비밀 번호</label>
            <input type="password" id="password" name="password" required>
            
            <input type="submit" value="확    인">
        </form>
    </div>
</body>
</html>

templates/ramen/init_cs_power.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>init_cs_power</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" v  href="{% static '/css/style.css' %}">
</head>
<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-bagic.png' %}" class="bg-logo" alt="">
        <img src="{% static '/img/kitchen-bg.jpg' %}" class="bg" alt="">
    </section>
    <!-- <h2 style="text-align: center;">상위박스 -거터 있음 / 하위박스 - 가로로 배치</h2> -->
    <section id="type1" class="content"  data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <h3 class="subtitle">기다리지 않고 빠르게</h3>
                <h2 class="title">여기에서<br>주문하세요!</h2>
                <div class="touch">
                    <img src="{% static '/img/touth-black.png' %}" class="hand" alt="#">
                    <P>화면을 터치해 주세요.</P>
                </div>
            </div>
            
            <div class="box02">
                <a href="{% url 'Ramen:index02'%}" class="info">
                    <img src="{% static '/img/fork-white.png' %}" class="hand" alt="#">
                    <p class="btn">주문하기</p>
                </a>
            </div>
        </div>
    </section>
</body>
</html>

templates/ramen/new_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" v  href="{% static '/css/style.css' %}">
</head>
<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-bagic.png' %}" class="bg-logo" alt="">
        <img src="{% static '/img/kitchen-bg.jpg' %}" class="bg" alt="">
    </section>
    <!-- <h2 style="text-align: center;">상위박스 -거터 있음 / 하위박스 - 가로로 배치</h2> -->
    <section id="type1" class="content"  data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <h3 class="subtitle">기다리지 않고 빠르게</h3>
                <h2 class="title">여기에서<br>주문하세요!</h2>
                <div class="touch">
                    <img src="{% static '/img/touth-black.png' %}" class="hand" alt="#">
                    <P>화면을 터치해 주세요.</P>
                </div>
            </div>
            
            <div class="box02">
                <a href="{% url 'Ramen:index02'%}" class="info">
                    <img src="{% static '/img/fork-white.png' %}" class="hand" alt="#">
                    <p class="btn">주문하기</p>
                </a>
            </div>
        </div>
    </section>
</body>
</html>

templates/ramen/new_index02.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" v  href="{% static '/css/style 02.css' %}">
</head>
<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-white.png' %}" class="bg-logo" alt="">
        <img src="{% static '/img/raman-03.jpg' %}" class="bg" alt="">
        <div class="bg-box"></div>
    </section>
    <!-- <h2 style="text-align: center;">상위박스 -거터 있음 / 하위박스 - 가로로 배치</h2> -->
    <section id="type1" class="content"  data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <h3 class="subtitle">기다리지 않고 빠르게</h3>
                <h2 class="title">여기에서<br>주문하세요!</h2>
                <div class="touch">
                    <img src="{% static 'img/touth-white-17-18.png'%}" class="hand" alt="#">
                    <P>화면을 터치해 주세요.</P>
                </div>
            </div>
            
            <div class="box02">

                    <a href="{% url 'Ramen:index04' %}" class="left">
                    <img src="{% static 'img/shopping-white.png' %}" class="shopping" alt="#">
                    <p class="btn">일반주문</p>
                </a>
                <!-- 음성기능 미지원으로 제거 2024.08.30 IJ.YI-->
                    <!-- <a href="{% url 'Ramen:index03' %}" class="right">
                    <img src="{% static 'img/voice--white.png'%}" class="voice" alt="#">
                    <p class="btn">음성주문</p> -->
                </a>
            </div>
        </div>
    </section>
</body>
</html>

templates/ramen/new_index03.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style 03.css' %}">
</head>
<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-white.png' %}" class="bg-logo" alt="">
        <a href="{% url 'Ramen:index02' %}" class="back"><img src="{% static '/img/back-19.png' %}" class="back" alt=""></a>
        <img src="{% static '/img/raman-03.jpg' %}" class="bg" alt="">
        <div class="bg-box"></div>
    </section>
    <section id="type1" class="content" data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <h3 class="subtitle"></h3>
                <h2 class="title">주문수량을 말씀해 주세요</h2>
                <p id="result" class="subtitle"></p>
            </div>
            <div class="box02">
                <div class="info">
                    <img src="{% static 'img/mic--white.png' %}" class="mic" alt="#">
                    <p class="btn">말씀해주세요</p>
                </div>
            </div>
        </div>
    </section>

    <!-- 외부 JavaScript 파일을 불러옵니다 -->
    <script src="{% static 'js/voice_order.js' %}"></script>
</body>
</html>

templates/ramen/new_index04.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100..900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style 04.css' %}">
</head>

<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-white.png' %}" class="bg-logo" alt="">
        <img src="{% static '/img/raman-03.jpg' %}" class="bg" alt="">
        <div class="bg-box"></div>
    </section>
    <section id="type1" class="content" data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <h3 class="subtitle">주문수량 확인중</h3>
            </div>
            <div class="box02">
                <div class="info">
                    <!-- 수량 계산을 위한 버튼 -->
                    <a href="#" class="left" id="decrease"><img src="{% static '/img/left.png' %}" alt=""></a>
                    <p class="count" id="count">0</p>
                    <a href="#" class="right" id="increase"><img src="{% static '/img/right-plus.png' %}" alt=""></a>
                </div>
            </div>
            <div class="box03">
                <a href="{% url 'Ramen:index' %}" class="left">
                    <img src="{% static '/img/again.png' %}" class="again" alt="#">
                    <p class="btn">다시주문</p>
                </a>
                <!-- 수량 값을 URL 파라미터로 전달 -->
                <a href="#" id="confirm" class="right" data-confirm-url="{% url 'Ramen:db_index00' %}">
                    <img src="{% static '/img/check.png' %}" class="check" alt="#">
                    <p class="btn">확 인</p>
                </a>
            </div>
        </div>
    </section>

    <!-- 외부 JavaScript 파일을 불러옵니다 -->
    <script src="{% static 'js/order_count.js' %}"></script>
</body>

</html>

templates/ramen/new_index05.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abiman | Dining-bot</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style 05.css' %}">
</head>
<body>
    <header id="header"></header>
    <div class="page_btn"></div>
    <section id="visual" data-page-btn="Home">
        <img src="{% static '/img/ABIMAN-CI-white.png' %}" class="bg-logo" alt="">
        <img src="{% static '/img/raman-03.jpg' %}" class="bg" alt="">
        <div class="bg-box"></div>
    </section>
    <section id="type1" class="content" data-page-btn="Service">
        <div class="inner">
            <div class="box01">
                <img src="{% static '/img/end.png' %}" class="end" alt="">
            </div>
            <div class="box02">
                <div class="info">
                    <!-- URL 파라미터에서 수량 값을 가져와서 표시 -->
                    <p class="btn" id="displayCount">0</p>
                </div>
            </div>
        </div>
    </section>

    <!-- JavaScript 파일에서 사용할 URL을 HTML 속성에 전달 -->
    <script>
        var redirectUrl = "{% url 'Ramen:index' %}";
    </script>
    <script src="{% static 'js/display_count.js' %}"></script>
</body>
</html>